# All available configuration can be found here:
# https://www.algolia.com/doc/api-client/symfony/configuration/
algolia_search:
  doctrineSubscribedEvents: ['postPersist']
  indices:
    - name: produits
      class: App\Entity\Produit
      enable_serializer_groups: true

  
