# All available configuration can be found here:
# https://www.algolia.com/doc/api-client/symfony/configuration/
algolia_search:
  doctrineSubscribedEvents: ['postPersist', 'postUpdate', 'preRemove']
  indices:
    - name: products
      class: App\Entity\Produit
      enable_serializer_groups: true