vich_uploader:
    db_driver: orm

    mappings:
        photos:
            uri_prefix: /images/produits
            upload_destination: '%kernel.project_dir%/public/images/produits'

        images_multiples:
            uri_prefix: /images/images_produit
            upload_destination: '%kernel.project_dir%/public/images/images_produit'
